apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: igx6jf7xf-java-springboot
  janus-idp.io/tekton: igx6jf7xf-java-springboot
  backstage.io/kubernetes-id: igx6jf7xf-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: igx6jf7xf-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
