apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: igx6jf7xf-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/igx6jf7xf-java-springboot-gitops